import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:app/features/auth/providers/auth_provider.dart';
import '../models/doctor.dart';
import '../models/specialty.dart';
import '../services/api_service.dart';
import 'doctor_detail_page.dart';
import 'home_shell.dart';
import '../widgets/doctor_card.dart';

class BookingHomePage extends StatefulWidget { const BookingHomePage({super.key}); @override State<BookingHomePage> createState()=>_S(); }
class _S extends State<BookingHomePage>{
  List<Doctor> doctors=[]; List<Specialty> specialties=[]; bool loading=true; String? error; String query=''; String selected='';
  @override void initState(){super.initState();load();}
  Future<void> load() async {setState(()=>loading=true);try{final rawD=await ApiService.get('/doctors'); final rawS=await ApiService.get('/specialties'); final ds=(rawD as List).map((e)=>Doctor.fromJson(Map<String,dynamic>.from(e))).where((e)=>e.id.isNotEmpty).toList(); final ss=(rawS as List).map((e)=>Specialty.fromJson(Map<String,dynamic>.from(e))).where((e)=>e.status=='ACTIVE'&&e.name.isNotEmpty).toList(); if(mounted)setState((){doctors=ds;specialties=ss;loading=false;error=null;});}catch(e){if(mounted)setState((){loading=false;error='Không thể tải dữ liệu từ máy chủ.';});}}
  List<Doctor> get filtered=>doctors.where((d){final q=query.toLowerCase(); final okQ=q.isEmpty||d.name.toLowerCase().contains(q)||d.specialty.toLowerCase().contains(q);final okS=selected.isEmpty||d.specialty==selected;return okQ&&okS;}).toList();
  IconData iconFor(String name){final s=name.toLowerCase();if(s.contains('tim'))return Icons.favorite_rounded;if(s.contains('da'))return Icons.face_rounded;if(s.contains('nội'))return Icons.monitor_heart_rounded;if(s.contains('nhi'))return Icons.child_care_rounded;if(s.contains('răng'))return Icons.mood_rounded;if(s.contains('mắt'))return Icons.visibility_rounded;return Icons.medical_services_rounded;}
  @override Widget build(BuildContext context){final user=context.read<AuthProvider>().currentUser;return RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(20,16,20,100),children:[
    Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:const Color(0xffE0F2FE),borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.local_hospital_rounded,color:Color(0xff0284C7))),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Chào bạn 👋',style:TextStyle(color:Color(0xff64748B))),Text(user?.fullName??'Bạn',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w800))])),Container(width:44,height:44,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(14),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha: .05),blurRadius:12)]),child:const Icon(Icons.notifications_none_rounded))]),
    const SizedBox(height:20),
    Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xff0284C7),Color(0xff38BDF8)]),borderRadius:BorderRadius.circular(26)),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Đặt lịch khám\nnhanh chóng',style:TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.w800,height:1.15)),const SizedBox(height:8),const Text('Chọn bác sĩ phù hợp và thời gian thuận tiện cho bạn.',style:TextStyle(color:Colors.white70)),const SizedBox(height:16),ElevatedButton(onPressed:()=>context.findAncestorStateOfType<HomeShellState>()?.goTo(1),style:ElevatedButton.styleFrom(backgroundColor:Colors.white,foregroundColor:Color(0xff0369A1),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),child:const Text('Xem lịch hẹn'))])),const SizedBox(width:12),const Icon(Icons.calendar_month_rounded,color:Colors.white,size:70)])),
    const SizedBox(height:18),TextField(onChanged:(v)=>setState(()=>query=v),decoration:InputDecoration(hintText:'Tìm bác sĩ hoặc chuyên khoa...',prefixIcon:const Icon(Icons.search_rounded),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(17),borderSide:BorderSide.none))),
    const SizedBox(height:24),const Text('Chuyên khoa',style:TextStyle(fontSize:19,fontWeight:FontWeight.w800)),const SizedBox(height:12),
    SizedBox(height:104,child:specialties.isEmpty?const Center(child:Text('Chưa có chuyên khoa trong hệ thống',style:TextStyle(color:Color(0xff64748B)))):ListView.separated(scrollDirection:Axis.horizontal,itemCount:specialties.length,itemBuilder:(c,i){final s=specialties[i];final active=selected==s.name;return GestureDetector(onTap:()=>setState(()=>selected=active?'':s.name),child:AnimatedContainer(duration:const Duration(milliseconds:180),width:96,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:active?const Color(0xff0284C7):Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:active?const Color(0xff0284C7):const Color(0xffE2E8F0))),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(iconFor(s.name),color:active?Colors.white:const Color(0xff0284C7),size:27),const SizedBox(height:7),Text(s.name,maxLines:2,textAlign:TextAlign.center,overflow:TextOverflow.ellipsis,style:TextStyle(fontSize:11,fontWeight:FontWeight.w700,color:active?Colors.white:const Color(0xff334155)))])));},separatorBuilder:(_, __)=>const SizedBox(width:10))),
    const SizedBox(height:24),Row(children:[const Expanded(child:Text('Bác sĩ nổi bật',style:TextStyle(fontSize:19,fontWeight:FontWeight.w800))),if(selected.isNotEmpty)TextButton(onPressed:()=>setState(()=>selected=''),child:const Text('Bỏ lọc'))]),const SizedBox(height:10),
    if(loading) ...List.generate(3,(i)=>const Padding(padding:EdgeInsets.only(bottom:12),child:LinearProgressIndicator(minHeight:70,borderRadius:BorderRadius.all(Radius.circular(20)))))
    else if(error!=null)Center(child:Column(children:[const Icon(Icons.cloud_off_rounded,size:48,color:Color(0xff94A3B8)),const SizedBox(height:8),Text(error!),TextButton(onPressed:load,child:const Text('Thử lại'))]))
    else if(filtered.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Center(child:Text('Chưa có bác sĩ phù hợp.',style:TextStyle(color:Color(0xff64748B)))))
    else ...filtered.take(8).map((d)=>Padding(padding:const EdgeInsets.only(bottom:12),child:DoctorCard(doctor:d,onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>DoctorDetailPage(doctor:d))))))
  ]));}
}
