import 'package:flutter/material.dart';
import '../services/admin_api.dart';
class AdminApp extends StatefulWidget{const AdminApp({super.key});@override State<AdminApp> createState()=>_S();}
class _S extends State<AdminApp>{final api=AdminApi();Map<String,dynamic>? user;String page='Dashboard';bool loading=false;@override Widget build(BuildContext context)=>user==null?_login():_dashboard();
 Widget _login()=>Scaffold(backgroundColor:const Color(0xffF1F5F9),body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(26)),child:Padding(padding:const EdgeInsets.all(30),child:_Login(api:api,onOk:(u)=>setState(()=>user=u)))))));
 Widget _dashboard()=>Scaffold(backgroundColor:const Color(0xffF6F8FC),body:Row(children:[Container(width:240,color:const Color(0xff0F172A),padding:const EdgeInsets.symmetric(vertical:26,horizontal:16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Padding(padding:EdgeInsets.all(12),child:Text('HEALTHCARE',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:19))),const SizedBox(height:25),...['Dashboard','Người dùng','Bác sĩ','Chuyên khoa','Lịch hẹn'].map((x)=>ListTile(onTap:()=>setState(()=>page=x),selected:page==x,selectedTileColor:const Color(0xff1E293B),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12)),leading:Icon(_icon(x),color:Colors.white70),title:Text(x,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w600)))),const Spacer(),ListTile(onTap:()=>setState(()=>user=null),leading:const Icon(Icons.logout,color:Colors.white70),title:const Text('Đăng xuất',style:TextStyle(color:Colors.white)))]),),Expanded(child:Column(children:[Container(height:76,color:Colors.white,padding:const EdgeInsets.symmetric(horizontal:28),child:Row(children:[Text(page,style:const TextStyle(fontSize:23,fontWeight:FontWeight.w800)),const Spacer(),CircleAvatar(backgroundColor:const Color(0xffE0F2FE),child:const Icon(Icons.admin_panel_settings,color:Color(0xff0284C7))),const SizedBox(width:10),Text(user?['fullName']??'Admin',style:const TextStyle(fontWeight:FontWeight.w700))])),Expanded(child:_content())]))]);
 IconData _icon(String x)=>{'Dashboard':Icons.dashboard_rounded,'Người dùng':Icons.people_alt_rounded,'Bác sĩ':Icons.medical_services_rounded,'Chuyên khoa':Icons.category_rounded,'Lịch hẹn':Icons.calendar_month_rounded}[x]??Icons.circle;
 Widget _content(){switch(page){case'Người dùng':return _users();case'Bác sĩ':return _simpleList('/doctors','Bác sĩ');case'Chuyên khoa':return _simpleList('/specialties','Chuyên khoa');case'Lịch hẹn':return _simpleList('/admin/appointments','Lịch hẹn');default:return _stats();}}
 Widget _stats()=>FutureBuilder(future:api.req('GET','/admin/stats'),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final d=Map<String,dynamic>.from(s.data as Map);return ListView(padding:const EdgeInsets.all(28),children:[Wrap(spacing:16,runSpacing:16,children:[_stat('Người dùng',d['users'],Icons.people_alt_rounded),_stat('Bác sĩ',d['doctors'],Icons.medical_services_rounded),_stat('Chuyên khoa',d['specialties'],Icons.category_rounded),_stat('Lịch hẹn',d['appointments'],Icons.calendar_month_rounded)]),const SizedBox(height:25),Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:const Text('Hệ thống đang lấy thống kê trực tiếp từ MongoDB thông qua API.',style:TextStyle(fontSize:16,color:Color(0xff475569))) )]);});
 Widget _stat(String t,d,IconData i)=>Container(width:220,padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:const Color(0xffE0F2FE),borderRadius:BorderRadius.circular(14)),child:Icon(i,color:const Color(0xff0284C7))),const SizedBox(width:13),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$d',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)),Text(t,style:const TextStyle(color:Color(0xff64748B)))])]);
 Widget _users()=>FutureBuilder(future:api.req('GET','/admin/users'),builder:(c,s){if(s.hasError)return Center(child:Text('${s.error}'));if(!s.hasData)return const Center(child:CircularProgressIndicator());final list=(s.data as List);return ListView(padding:const EdgeInsets.all(28),children:[Text('Tổng ${list.length} người dùng',style:const TextStyle(color:Color(0xff64748B))),const SizedBox(height:14),...list.map((u)=>Card(elevation:0,child:ListTile(leading:CircleAvatar(backgroundColor:const Color(0xffE0F2FE),child:const Icon(Icons.person,color:Color(0xff0284C7))),title:Text(u['fullName']??''),subtitle:Text('${u['email']??''} • ${u['role']??''}'),trailing:Text(u['status']??''))))]);});
 Widget _simpleList(String path,String title)=>FutureBuilder(future:api.req('GET',path),builder:(c,s){if(s.hasError)return Center(child:Text('${s.error}'));if(!s.hasData)return const Center(child:CircularProgressIndicator());final list=s.data is Map?(s.data['data']??[]):s.data;return ListView(padding:const EdgeInsets.all(28),children:[Text('Dữ liệu $title đang đồng bộ từ API.',style:const TextStyle(color:Color(0xff64748B))),const SizedBox(height:14),...(list as List).map((x)=>Card(elevation:0,child:ListTile(title:Text('${x['name']??x['fullName']??x['_id']??'Bản ghi'}'),subtitle:Text('${x['specialty']??x['status']??''}'))))]);});}
class _Login extends StatefulWidget{final AdminApi api;final ValueChanged<Map<String,dynamic>> onOk;const _Login({required this.api,required this.onOk});@override State<_Login> createState()=>_L();}
class _L extends State<_Login>{final e=TextEditingController(),p=TextEditingController();bool busy=false;String? err;@override Widget build(BuildContext c)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:62,height:62,decoration:BoxDecoration(color:const Color(0xffDBEAFE),borderRadius:BorderRadius.circular(18)),child:const Icon(Icons.admin_panel_settings,color:Color(0xff2563EB),size:34)),const SizedBox(height:20),const Text('Quản trị hệ thống',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:5),const Text('Đăng nhập bằng tài khoản có role ADMIN.',style:TextStyle(color:Color(0xff64748B))),const SizedBox(height:24),TextField(controller:e,decoration:const InputDecoration(labelText:'Email',prefixIcon:Icon(Icons.mail_outline))),const SizedBox(height:14),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'Mật khẩu',prefixIcon:Icon(Icons.lock_outline))),if(err!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(err!,style:const TextStyle(color:Colors.red))),const SizedBox(height:20),SizedBox(width:double.infinity,height:50,child:ElevatedButton(onPressed:busy?null : _login,style:ElevatedButton.styleFrom(backgroundColor:const Color(0xff2563EB),foregroundColor:Colors.white),child:busy?const CircularProgressIndicator(color:Colors.white):const Text('Đăng nhập')))]);Future<void> _login()async{setState(()=>busy=true);try{final u=await widget.api.login(e.text.trim(),p.text);if(u['role']!='ADMIN')throw Exception('Tài khoản này không có quyền ADMIN.');widget.onOk(u);}catch(x){setState(()=>err=x.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>busy=false);}}
}
